server:
  address: ${SERVER_HOST:127.0.0.1}
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: bank
  config:
    import:
      - optional:file:../config/${spring.application.name}/.env[.properties]

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true