server:
  address: ${SERVER_HOST:127.0.0.1}
  port: ${SERVER_PORT:8080}

# API Documentation
api:
  version: ${API_VERSION:v1.0-dev}
  versionPath: ${API_VERSION_PATH:v1}

spring:
  application:
    name: BANK
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:file:.env
      - optional:file:./saviing-bank/.env
      - optional:file:../config/bank/.env[.properties]
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
        - src/main/resources

  # Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/bank?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

# OAuth2 설정
oauth2:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}

logging:
  config: file:${LOGGING_CONFIG_PATH:../config/common/logback-spring.xml}
  level:
    saviing: DEBUG

springdoc:
  api-docs:
    path: /${api.versionPath}/api-docs
    enabled: true
  swagger-ui:
    path: /${api.versionPath}/swagger-ui.html
    title: SAVIING ${spring.application.name} API (Development)
    description: ${spring.application.name} 도메인 API 문서
    enabled: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    disable-swagger-default-url: true
  servers:
    - url: http://localhost:${server.port}
      description: Local Development Server
    - url: https://api.bank-dev.saviing.life
      description: Development Server

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized