server:
  address: ${SERVER_HOST:127.0.0.1}
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: BANK
  config:
    import:
      - optional:file:../config/${spring.application.name}/.env[.properties]

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  config: file:../config/common/logback-spring.xml
  level:
    saviing: DEBUG