server:
  address: ${SERVER_HOST:127.0.0.1}
  port: ${SERVER_PORT:8081}

# API Documentation
api:
  version: ${API_VERSION:v1.0-dev}
  versionPath: ${API_VERSION_PATH:v1}

spring:
  application:
    name: GAME
  config:
    import:
      - optional:file:../config/game/.env[.properties]

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
        - src/main/resources

logging:
  config: file:${LOGGING_CONFIG_PATH:../config/common/logback-spring.xml}
  level:
    saviing: DEBUG

springdoc:
  api-docs:
    path: /${api.versionPath}/api-docs
    enabled: true
  swagger-ui:
    path: /${api.versionPath}/swagger-ui.html
    title: SAVIING ${spring.application.name} API (Development)
    description: ${spring.application.name} 도메인 API 문서
    enabled: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    disable-swagger-default-url: true
  servers:
    - url: http://localhost:${server.port}
      description: Local Development Server
    - url: https://api.game-dev.saviing.life
      description: Development Server

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized